name: run-bots

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python bots/threatintel.py
        env:
          INTEL_TOKEN: ${{ secrets.INTEL_TOKEN }}
          INTEL_CHAT: ${{ secrets.INTEL_CHAT }}

      - run: python bots/redteam.py
        env:
          RED_TOKEN: ${{ secrets.RED_TOKEN }}
          RED_CHAT: ${{ secrets.RED_CHAT }}

      - run: python bots/blueteam.py
        env:
          BLUE_TOKEN: ${{ secrets.BLUE_TOKEN }}
          BLUE_CHAT: ${{ secrets.BLUE_CHAT }}

      # 🔥 salva histórico (ESSENCIAL)
      - name: Save history
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add sent_alerts.txt
          git commit -m "update history" || echo "no changes"
          git push
